/**
 * Regression suite for the production scoring engine.
 *
 * The expected values below PIN CURRENT BEHAVIOR — they were generated by
 * running the shipped formulas (including evidence blending) on the inputs,
 * not derived from the methodology prose. If a test here fails, either the
 * model changed (update the values AND the methodology page in the same PR)
 * or a bug crept in. The 2026-10 external review happened precisely because
 * no such pins existed.
 */
import { describe, it, expect } from 'vitest';
import {
  calculateReviewRankScore,
  bayesianRating,
  volumeScore,
  sentimentScore,
  consistencyScore,
  getRankLabel,
  BusinessReview,
} from '../reviewRankScoring';

function reviews(ratings: number[]): BusinessReview[] {
  return ratings.map((rating, i) => ({
    id: String(i),
    rating,
    text: '',
    createdAt: '2026-01-01T00:00:00.000Z',
    platform: 'google' as const,
  }));
}

function score(rating: number, count: number, sample: number[] = []) {
  return calculateReviewRankScore({
    businessId: 'test',
    rating,
    totalReviewCount: count,
    reviews: reviews(sample),
  });
}

const close = (x: number) => expect.closeTo(x, 5);

describe('known-value pins', () => {
  it('methodology example: 4.7★ / 412 reviews / sample 5,5,4,5,5 → 82.4', () => {
    const r = score(4.7, 412, [5, 5, 4, 5, 5]);
    expect(r.finalScore).toBeCloseTo(82.4, 5);
    expect(r.rankLabel).toBe('Elite');
    expect(r.componentScores).toEqual({
      bayesian: close(84.1),
      volume: close(79.2),
      sentiment: close(85.6), // post-blending (sample weight √(5/412) ≈ 0.11)
      consistency: close(74.8),
    });
  });

  it('small competitor: 4.9★ / 18 reviews / sample 5,5,5,5,4 → 72.5', () => {
    const r = score(4.9, 18, [5, 5, 5, 5, 4]);
    expect(r.finalScore).toBeCloseTo(72.5, 5);
    expect(r.componentScores.volume).toBeCloseTo(38.7, 5);
  });
});

describe('boundary: review counts (rating 4.5, no sample)', () => {
  it.each([
    [0, 51.8],
    [1, 54.1],
    [14, 62.9],
    [15, 63.2],
    [100, 71.1],
    [1999, 79.9],
    [2000, 79.9], // volume saturates exactly at 2,000
    [2001, 79.9], // …and clamps beyond it
    [1_000_000, 80.0],
  ])('%s reviews → %s', (count, expected) => {
    expect(score(4.5, count as number).finalScore).toBeCloseTo(expected as number, 5);
  });

  it('volume component saturates at 2,000 reviews', () => {
    expect(volumeScore(2000)).toBeCloseTo(100, 5);
    expect(volumeScore(2001)).toBeCloseTo(100, 5);
    expect(volumeScore(0)).toBeCloseTo(0, 5);
  });
});

describe('boundary: ratings (100 reviews, no sample)', () => {
  it.each([
    [1.0, 19.6],
    [4.0, 55.4],
    [5.0, 86.8],
  ])('rating %s → %s', (rating, expected) => {
    expect(score(rating as number, 100).finalScore).toBeCloseTo(expected as number, 5);
  });

  it('bayesian returns the 0–100 mapping (3.0★→0, 5.0★→100) after shrinkage toward the 4.2 prior', () => {
    // bayesianRating returns the mapped 0–100 score, not the raw 1–5 blend.
    expect(bayesianRating(4.2, 0)).toBeCloseTo(60.0, 10); // pure prior: (4.2−3)/2×100
    expect(bayesianRating(5.0, 1_000_000)).toBeCloseTo(100, 2); // prior influence vanishes
    expect(bayesianRating(3.0, 1_000_000)).toBeCloseTo(0, 2);
  });
});

describe('sentiment sets (rating 4.5, 100 reviews)', () => {
  it.each([
    [[5, 5, 5, 5, 5], 72.5],
    [[5, 5, 5, 5, 1], 68.9],
    [[1, 1, 1, 1, 1], 66.9],
    [[4, 4, 4, 4, 4], 70.8],
  ])('sample %j → %s', (sample, expected) => {
    expect(score(4.5, 100, sample as number[]).finalScore).toBeCloseTo(expected as number, 5);
  });

  it('v1.2 FIX: a mostly-great sample now outscores a uniformly bad one', () => {
    // Pre-v1.2 the consistency component rewarded uniformity even when it
    // was uniformly bad (1,1,1,1,1 → 69.1 beat 5,5,5,5,1 → 68.9). The
    // direction-aware consistency factor fixes the ordering.
    const uniformlyBad = score(4.5, 100, [1, 1, 1, 1, 1]).finalScore;
    const mostlyGreat = score(4.5, 100, [5, 5, 5, 5, 1]).finalScore;
    expect(mostlyGreat).toBeGreaterThan(uniformlyBad);
  });

  it('v1.2: direction-aware consistency — uniformity only counts when the sample is good', () => {
    expect(consistencyScore(reviews([1, 1, 1, 1, 1]))).toBe(0); // reliably bad ≠ reliable
    expect(consistencyScore(reviews([3, 3, 3, 3, 3]))).toBe(0); // uniform mediocrity
    expect(consistencyScore(reviews([4, 4, 4, 4, 4]))).toBeCloseTo(100, 5); // full credit from 4.0★
    expect(consistencyScore(reviews([3, 4, 3, 4, 4]))).toBeCloseTo(40.4, 1); // partial fade
  });

  it('v1.2: sample-evidence weight is capped at 0.5 even when the sample covers all reviews', () => {
    // 4.9★/18 reviews: uncapped weight would be √(5/18) ≈ 0.527; the cap
    // holds blended sentiment at 92.5 (= 90×0.5 + 95×0.5) instead of 92.4.
    const r = score(4.9, 18, [5, 5, 5, 5, 4]);
    expect(r.componentScores.sentiment).toBeCloseTo(92.5, 5);
    expect(r.componentScores.consistency).toBeCloseTo(74.2, 1);
    expect(r.finalScore).toBeCloseTo(72.5, 5);
  });
});

describe('missing / degenerate data is deterministic and documented', () => {
  it('no sample at all: sentiment=prior(rating), consistency=75, blending weight 0', () => {
    const r = score(4.7, 412, []);
    expect(r.componentScores.sentiment).toBeCloseTo(85.0, 5); // (4.7−3)/2×100
    expect(r.componentScores.consistency).toBeCloseTo(75.0, 5);
  });

  it('sample present but all ratings zero: raw sentiment neutral 50, consistency 75', () => {
    expect(sentimentScore(reviews([0, 0, 0]))).toBe(50);
    expect(consistencyScore(reviews([0, 0, 0]))).toBe(75);
    expect(score(4.5, 100, [0, 0, 0]).finalScore).toBeCloseTo(70.4, 5);
  });

  it('single rated review: consistency falls back to 75 (needs ≥2)', () => {
    expect(consistencyScore(reviews([5]))).toBe(75);
  });

  it('two identical reviews: perfect consistency', () => {
    expect(consistencyScore(reviews([5, 5]))).toBe(100);
    expect(score(4.5, 100, [5, 5]).finalScore).toBeCloseTo(72.0, 5);
  });

  it('zero reviews everywhere still produces a bounded, finite score', () => {
    const r = score(0, 0, []);
    expect(Number.isFinite(r.finalScore)).toBe(true);
    expect(r.finalScore).toBeGreaterThanOrEqual(0);
    expect(r.finalScore).toBeLessThanOrEqual(100);
  });
});

describe('labels', () => {
  it('getRankLabel delegates to the central band map', () => {
    expect(getRankLabel(82.4)).toBe('Elite');
    expect(getRankLabel(34.9)).toBe('Limited Reputation');
  });
});
